### ISSUE TITLE
Support font scaling

### ISSUE THREAD

**Issue by catgirladdict** [catgirladdict/AnimeOS#12]
Our font is 8x8 per character, so the depending on the users monitor it may be very hard to see the text.

Font scaling would entail both scaling the font and automatically choosing the scaling factor based on resolution.

**Comment by respectable-citizen** [comment]
Added in bd351d6e6295c3d2d945973d4661cf3d0eb5ea9b. The scaling system is pretty basic for now and doesn't have super high granularity. Also, the scaling isn't decided dynamically but it should be fine for now.
